### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by poprocks321** [arxhr007/Gamer-tux#1]
Going through the commands leads to it saying: "   /usr/bin/games: 1: Syntax error: "(" unexpected   " idk if you will get this but i am using kali linux and i also did it both in and out of root so i'm unsure.

**Comment by arxhr007** [comment]
# FIXED 

## Thanks for reporting this issue! ,it was a Shebang Error , i forgot to add ```#!/bin/bash``` at the first line
## It has been fixed in [here](https://github.com/arxhr007/Gamer-tux/commit/b2a6444db1f10f753ed591900807a8ccaf8dc8ca)
## Try running the same commands agian ;)

**Comment by poprocks321** [comment]
yeah its all working good now thanks for the fix
